# Generated by Django 5.2 on 2025-11-29 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMedicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('patient_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('patient_blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True)),
                ('patient_allergies', models.TextField(blank=True, null=True)),
                ('patient_existing_conditions', models.TextField(blank=True, null=True)),
                ('record_active', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
            options={
                'verbose_name': 'Patient Medical Data',
                'verbose_name_plural': 'Patient Medical Data',
                'db_table': 'patient_medical_data',
            },
        ),
    ]
