# Generated by Django 5.2 on 2025-11-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_first_name', models.CharField(max_length=50)),
                ('patient_last_name', models.CharField(max_length=50)),
                ('patient_birth_date', models.DateField()),
                ('patient_age', models.IntegerField()),
                ('patient_email', models.EmailField(max_length=100, unique=True)),
                ('patient_phone', models.CharField(max_length=15)),
                ('patient_gender', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=15)),
                ('record_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'db_table': 'patient',
            },
        ),
    ]
