# Generated by Django 5.2 on 2025-11-29 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('preassure_systolic', models.IntegerField(blank=True, null=True)),
                ('preassure_diastolic', models.IntegerField(blank=True, null=True)),
                ('record_diagnosis', models.TextField(blank=True, null=True)),
                ('record_active', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
            options={
                'verbose_name': 'Health Record',
                'verbose_name_plural': 'Health Records',
                'db_table': 'health_record',
                'ordering': ['-record_date'],
            },
        ),
    ]
